### ISSUE TITLE
Double newline in yaml

### ISSUE THREAD

**Issue by reactormonk** [dhall-lang/dhall-json#56]
```
{ x = ''foo
bar
'' }
```
gives
```
$ dhall-to-yaml < bug.dhall 
x: ! 'foo

  bar

'
```

**Comment by Gabriel439** [comment]
@reactormonk: See: https://github.com/snoyberg/yaml/issues/152

The summary of that issue is that the result is technically correct, but probably undesirable.  However, that issue is now fixed and the default behavior in `yaml-0.10.2.0` now does what you expect:

```
$ dhall-to-yaml <<< './bug.dhall' 
x: |
  foo
  bar

```

I just updated `dhall-json` to build against the latest version of `yaml` in https://github.com/dhall-lang/dhall-json/pull/57 so the next release will have the desired behavior.
